# https://wiki.hyprland.org/Configuring/Variables/#input
input {
  kb_layout = us
  kb_variant = intl
  kb_model =
  kb_options = nodeadkeys,ctrl:nocaps,compose:ralt
  kb_rules =

  follow_mouse = 1

  sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

  touchpad {
    natural_scroll = false
  }
}

# Scroll nicely in the terminal
windowrule = match:class (Alacritty|kitty), scroll_touchpad 1.5
windowrule = match:class com.mitchellh.ghostty, scroll_touchpad 0.2

# Enable touchpad gestures for changing workspaces
# https://wiki.hypr.land/Configuring/Gestures/
gesture = 3, horizontal, workspace

# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
device {
  name = logitech-g502-hero-gaming-mouse
  sensitivity = -0.5
}
