# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale
# You must relaunch Hyprland after changing any envs

# monitor=,preferred,auto,auto
monitor=eDP-1,1920x1080@120,0x0,1
monitor=HDMI-A-1,1920x1080@60,1920x0,1

