# Ref https://wiki.hyprland.org/Configuring/Window-Rules
# Ref https://wiki.hyprland.org/Configuring/Workspace-Rules

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class .*

# Float and center settings and previews
windowrule = float on, match:class ^(blueberry.py|Impala|Btop|org.gnome.NautilusPreviewer)$
windowrule = center on, match:class ^(blueberry.py|Impala|Btop|org.gnome.NautilusPreviewers$
windowrule = size 1000 800, match:class ^(blueberry.py|Impala|Btop|org.gnome.NautilusPreviewer)$

# Float and center file pickers
windowrule = float on, match:class xdg-desktop-portal-gtk, match:title ^(Open.*Files?|Save.*Files?|All Files|Save)
windowrule = center on, match:class xdg-desktop-portal-gtk, match:title ^(Open.*Files?|Save.*Files?|All Files|Save)

# Float Steam
windowrule = float on, match:class steam
windowrule = center on, match:class steam, match:title Steam
windowrule = opacity 1 1, match:class steam
windowrule = size 1100 700, match:class steam, match:title Steam
windowrule = size 460 800, match:class steam, match:title Friends List
windowrule = idle_inhibit fullscreen, match:class steam

# Pavucontrol floating
windowrule = float on, match:class (.*org.pulseaudio.pavucontrol.*)
windowrule = size 700 600, match:class (.*org.pulseaudio.pavucontrol.*)
windowrule = center on, match:class (.*org.pulseaudio.pavucontrol.*)
#windowrule = pin,class:(.*org.pulseaudio.pavucontrol.*)

# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0

