# Ref https://wiki.hyprland.org/Configuring/Window-Rules
# Ref https://wiki.hyprland.org/Configuring/Workspace-Rules

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Float and center settings and previews
windowrule = float, class:^(blueberry.py|Impala|Btop|org.gnome.NautilusPreviewer)$
windowrule = center, class:^(blueberry.py|Impala|Btop|org.gnome.NautilusPreviewers$
windowrule = size 1000 800, class:^(blueberry.py|Impala|Btop|org.gnome.NautilusPreviewer)$

# Float and center file pickers
windowrule = float, class:xdg-desktop-portal-gtk, title:^(Open.*Files?|Save.*Files?|All Files|Save)
windowrule = center, class:xdg-desktop-portal-gtk, title:^(Open.*Files?|Save.*Files?|All Files|Save)

# Float Steam, fullscreen RetroArch
windowrule = float, class:steam
windowrule = center, class:steam, title:Steam

# Pavucontrol floating
windowrulev2 = float,class:(.*org.pulseaudio.pavucontrol.*)
windowrulev2 = size 700 600,class:(.*org.pulseaudio.pavucontrol.*)
windowrulev2 = center,class:(.*org.pulseaudio.pavucontrol.*)
#windowrulev2 = pin,class:(.*org.pulseaudio.pavucontrol.*)

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

