set -g status on
set -g status-interval 5
set -g status-justify left
set -g status-bg "#0f111a"
set -g status-fg "#e0e0e0"
set -g status-left-length 100
set -g status-right-length 100
set -g pane-border-style fg="#616161"
set -g pane-active-border-style fg="#2979FF"

setw -g window-status-format "#[bg=#0f111a,fg=#f5f5f5]#[bg=#f5f5f5,fg=#0f111a]#I #[bg=#1c252b,fg=#e0e0e0] #W#[bg=#0f111a,fg=#1c252b]#[default]"
setw -g window-status-current-format "#[bg=#00e676,fg=#0f111a] #I #[bg=#1c252b,fg=#e0e0e0] #W #[default]"
set -g status-left ""
set -g status-right "#(gitmux -cfg ~/.config/tmux/gitmux.conf '#{pane_current_path}')"
set -ag status-right "#[bg=#0f111a,fg=#ff1744]#[bg=#ff1744,fg=#0f111a] #[bg=#0f111a,fg=#f5f5f5] #(tmux display-message -p '#{pane_current_command}') #[default]"
set -ag status-right "#[bg=#0f111a,fg=#ffd600]#[bg=#ffd600,fg=#0f111a] #[bg=#0f111a,fg=#f5f5f5] #(top -bn1 | grep 'Cpu(s)' | awk '{print $2 + $4}')% #[default]"
set -ag status-right "#[bg=#0f111a,fg=#00e676]#[bg=#00e676,fg=#0f111a] #[bg=#0f111a,fg=#f5f5f5] #S #[default]"
setw -g mode-style bg='#1c252b',fg='#e0e0e0'
set -g message-style bg='#1c252b',fg='#e0e0e0'
