# ---------------- [[ Options  ]] ----------------

# Set true color
set-option -sa terminal-overrides ",xterm*:Tc"
set -g default-terminal "tmux-256color"
set -g mouse on

# Set status line to be on top
set-option -g status-position top

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Set Vi Mode
set-window-option -g mode-keys vi

# ---------------- [[ Bindings ]] ----------------

# Set prefix bind
unbind C-b
set -g prefix C-Space
bind C-space send-prefix

# Set key to reload config
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# Window Management - Open in current path
bind = split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Resizing windows 
bind -r j resize-pane -D 5 # Move Pane down
bind -r k resize-pane -U 5 # Move Pane up 
bind -r l resize-pane -R 5 # Move Pane right
bind -r h resize-pane -L 5 # Move Pane left 

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

# Vi mode bindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# ------------- [[ Display Popups]] --------------

bind C-g display-popup \
  -d "#{pane_current_path}" \
  -w 80% \
  -h 80% \
  -E "lazygit"
bind C-e display-popup \
  -d "#{pane_current_path}" \
  -w 80% \
  -h 80% \
  -E "yazi"
bind C-n display-popup -E 'bash -i -c "read -p \"Session name: \" name; tmux new-session -d -s \$name && tmux switch-client -t \$name"'
bind C-j display-popup -E "tmux list-sessions | sed -E 's/:.*$//' | grep -v \"^$(tmux display-message -p '#S')\$\" | fzf --reverse | xargs tmux switch-client -t"

bind d display-menu -T "#[align=centre]Dotfiles" -x C -y C \
  "zshrc"             z  "display-popup -w 80% -h 80% -E 'nvim ~/.config/zsh/.zshrc'" \
  "tmux"              t  "display-popup -w 80% -h 80% -E 'nvim ~/.config/tmux/tmux.conf'" \
  "nvim"              n  "display-popup -w 80% -h 80% -E 'nvim ~/.config/nvim/init.lua'" \
  "hyprland"          h  "display-popup -w 80% -h 80% -E 'nvim ~/.config/hypr/hyprland.conf'" \
  "waybar"            w  "display-popup -w 80% -h 80% -E 'nvim ~/.config/waybar/config.jsonc'" \
  "Exit"              q  ""

# ---------------- [[ Plugins  ]] ----------------

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
# set -g @plugin 'catppuccin/tmux'
# set -g @plugin 'janoamaral/tokyo-night-tmux'

# ---------------- [[ P-Config ]] ----------------

source-file ~/.config/tmux/themes/current.conf

# ---------------- [[ Startup  ]] ----------------

# Initialize TMUX plugin manager
run '~/.config/tmux/plugins/tpm/tpm'

# Make the status bar transparent -> place after run
set -g status-bg default
set -g status-style bg=default
