$font = JetBrainsMonoNerdFont

# GENERAL
general {
  hide_cursor = true
  ignore_empty_input = true
}

# BACKGROUND
background {
  monitor =
  # path = screenshot
  path = ~/.config/backgrounds/minimalist-bridge.jpg
  color = rgba(15, 17, 26, 1.0)
  blur_passes = 2
}

# ANIMATIONS
animations {
  enabled = true

  bezier = linear, 1, 1, 0, 0

  animation = fadeIn, 1, 1, linear
  animation = fadeOut, 1, 1, linear
}

# INPUT FIELD
input-field {
  monitor =
  size = 400, 50
  outline_thickness = 2

  outer_color = rgb(${bg})
  inner_color = rgb(${bg})
  font_color = rgb(${fg})
  check_color = rgb(${blue})
  fail_color = rgb(${red})
  capslock_color = rgb(${orange})

  font_color = rgb(143, 143, 143)
  fade_on_empty = false
  rounding = 5

  font_family = $font
  placeholder_text =
  fail_text =

  dots_text_format = *
  dots_size = 0.4
  dots_spacing = 0.3

  position = 0, -30%
  halign = center
  valign = center
}

# TIME
label {
  monitor =
  text = $TIME
  font_size = 80
  font_family = $font

  position = 0, -30%
  halign = center
  valign = top
}

# DATE
label {
  monitor =
  text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
  font_size = 25
  font_family = $font

  position = 0, -45%
  halign = center
  valign = top
}

