# Custom TMUX Theme

# # Deep Ocean Colorscheme
# set -g @color-bg           "0f111a"
# set -g @color-fg           "e0e0e0"
# set -g @color-muted        "616161"
# set -g @color-accent-1     "ff1744"   # red
# set -g @color-accent-2     "ffd600"   # yellow
# set -g @color-accent-3     "00e676"   # green
# set -g @color-accent-4     "00e5ff"   # cyan
# set -g @color-accent-5     "2979ff"   # blue
# set -g @color-accent-6     "d500f9"   # purple

# General Style
set -g status on
set -g status-interval 5
set -g status-justify left
set -g status-bg "#0f111a"     # background
set -g status-fg "#e0e0e0"     # foreground
set -g status-left-length 100
set -g status-right-length 100

# Borders
set -g pane-border-style fg="#616161"        # brightBlack (borda inativa)
set -g pane-active-border-style fg="#2979FF" # blue (borda ativa)

# Windows
setw -g window-status-format \
"#[bg=#0f111a,fg=#f5f5f5]"\
"#[bg=#f5f5f5,fg=#0f111a]#I "\
"#[bg=#1c252b,fg=#e0e0e0] #W"\
"#[bg=#0f111a,fg=#1c252b]"\
"#[default]"\

setw -g window-status-current-format \
"#[bg=#00e676,fg=#0f111a] #I "\
"#[bg=#1c252b,fg=#e0e0e0] #W "\
"#[default]"

# Status Left
set -g status-left ""

# Status Right
set -g status-right ""

# Status Right: Application
set -ag status-right \
"#[bg=#0f111a,fg=#ff1744]"\
"#[bg=#ff1744,fg=#0f111a] "\
"#[bg=#0f111a,fg=#f5f5f5] #(tmux display-message -p '#{pane_current_command}') "\
"#[default]"

# Status Right: CPU
set -ag status-right \
"#[bg=#0f111a,fg=#ffd600]"\
"#[bg=#ffd600,fg=#0f111a] "\
"#[bg=#0f111a,fg=#f5f5f5] #(top -bn1 | grep 'Cpu(s)' | awk '{print $2 + $4}')% "\
"#[default]"

# Status Right: Sessions
set -ag status-right \
"#[bg=#0f111a,fg=#00e676]"\
"#[bg=#00e676,fg=#0f111a] "\
"#[bg=#0f111a,fg=#f5f5f5] #S "\
"#[default]"

# Copy Mode
setw -g mode-style bg='#1c252b',fg='#e0e0e0'

# Messages
set -g message-style bg='#1c252b',fg='#e0e0e0'

