# Set programs that you use
$terminal = kitty
$fileManager = dolphin
$menu = rofi -show drun
$internetBrowser = firefox

# Power
bind = $mainMod SHIFT, SPACE, exec, hyprlock
bind = $mainMod,       M,     exec, wlogout
bind = $mainMod SHIFT, M,     exit

# Program launcher
bind = $mainMod, RETURN, exec, $terminal
bind = $mainMod, SPACE,  exec, $menu
bind = $mainMod, E,      exec, $fileManager
bind = $mainMod, B,      exec, $internetBrowser
bind = $mainMod, O,      exec, obsidian -disable-gpu

# Clipboard
bind = $mainMod, V, exec, cliphist list | rofi -dmenu | cliphist decode | wl-copy

# Screenshots
bind =               , PRINT, exec, hyprshot -m output -m active
bind =          SHIFT, PRINT, exec, hyprshot -m output -m active --clipboard-only
bind = $mainMod      , PRINT, exec, hyprshot -m region
bind = $mainMod SHIFT, PRINT, exec, hyprshot -m region           --clipboard-only

