return {}
-- return {
--   {
--     "folke/lazydev.nvim",
--     ft = "lua",
--     opts = {
--       library = {
--         { path = "${3rd}/luv/library", words = { "vim%.uv" } },
--       },
--     },
--   },
--   {
--     "neovim/nvim-lspconfig",
--     dependencies = {
--       -- Automatically install LSPs and related tools to stdpath for Neovim
--       -- Mason must be loaded before its dependents so we need to set it up here.
--       --  `opts = {}` is the same as calling `require('mason').setup({})`
--       { "mason-org/mason.nvim", opts = {} },
--       { "mason-org/mason-lspconfig.nvim" },
--       { "WhoIsSethDaniel/mason-tool-installer.nvim" },
--
--       -- Useful status updates for LSP.
--       { "j-hui/fidget.nvim", opts = {} },
--
--       -- Allows extra capabilities provided by blink.cmp
--       { "saghen/blink.cmp" },
--     },
--
--     config = function()
--       -- Extend capabilities for LSP
--       local capabilities = require("blink.cmp").get_lsp_capabilities()
--
--       -- Enable language servers
--       --  Add any additional override configuration in the following tables. Available keys are:
--       --  - cmd (table): Override the default command used to start the server
--       --  - filetypes (table): Override the default list of associated filetypes for the server
--       --  - capabilities (table): Override fields in capabilities. Can be used to disable certain LSP features.
--       --  - settings (table): Override the default settings passed when initializing the server.
--       local servers = {
--         ansiblels = {
--           cmd = { "ansible-language-server", "--stdio" },
--           filetypes = { "yaml", "yml" },
--           settings = {
--             ansible = {
--               ansible = {
--                 path = "ansible",
--               },
--               python = {
--                 interpreterPath = "python",
--               },
--               validation = {
--                 enabled = true,
--                 lint = {
--                   enabled = true,
--                   path = "ansible-lint",
--                 },
--               },
--             },
--           },
--         },
--       }
--
--       -- Ensure the servers are installed with mason
--       local ensure_installed = vim.tbl_keys(servers or {})
--       vim.list_extend(ensure_installed, {
--         "stylua", -- Used to format Lua code
--       })
--
--       require("mason-tool-installer").setup({ ensure_installed = ensure_installed })
--       ---@diagnostic disable-next-line: missing-fields
--       require("mason-lspconfig").setup({
--         ensure_installed = {}, -- let mason-tool-installer handle the instalation
--         automatic_instalation = false,
--         handlers = {
--           function(server_name)
--             local server = servers[server_name] or {}
--             -- This handles overriding only values explicitly passed
--             -- by the server configuration above. Useful when disabling
--             -- certain features of an LSP (for example, turning off formatting for ts_ls)
--             server.capabilities = vim.tbl_deep_extend("force", {}, capabilities, server.capabilities or {})
--             require("lspconfig")[server_name].setup(server)
--           end,
--         },
--       })
--
--       -- This function gets run when an LSP attaches to a particular buffer.
--       vim.api.nvim_create_autocmd("LspAttach", {
--         group = vim.api.nvim_create_augroup("lsp-attach", { clear = true }),
--         callback = function(event)
--           local map = function(keys, func, desc, mode)
--             mode = mode or "n"
--             vim.keymap.set(mode, keys, func, { buffer = event.buf, desc = "LSP: " .. desc })
--           end
--
--           -- stylua: ignore start
--           map('ghh', vim.lsp.buf.hover,                                          'Hover')
--           map('grn', vim.lsp.buf.rename,                                         'Rename')
--           map('gca', vim.lsp.buf.code_action,                                    'Goto Code Action', { 'n', 'x' })
--           map('grr', require('telescope.builtin').lsp_references,                'Goto References')
--           map('gip', require('telescope.builtin').lsp_implementations,           'Goto Implementation')
--           map('gdf', require('telescope.builtin').lsp_definitions,               'Goto Definition')
--           map('gdc', vim.lsp.buf.declaration,                                    'Goto Declaration')
--           map('gds', require('telescope.builtin').lsp_document_symbols,          'Open Document Symbols')
--           map('gws', require('telescope.builtin').lsp_dynamic_workspace_symbols, 'Open Workspace Symbols')
--           map('gtd', require('telescope.builtin').lsp_type_definitions,          'Goto Type Definition')
--
--           -- The following two autocommands are used to highlight references of the
--           -- word under your cursor when your cursor rests there for a little while.
--           --    See `:help CursorHold` for information about when this is executed
--           --
--           -- When you move your cursor, the highlights will be cleared (the second autocommand).
--           local client = vim.lsp.get_client_by_id(event.data.client_id)
--           if client and client_supports_method(client, vim.lsp.protocol.Methods.textDocument_documentHighlight, event.buf) then
--             local highlight_augroup = vim.api.nvim_create_augroup('lsp-highlight', { clear = false })
--             vim.api.nvim_create_autocmd({ 'CursorHold', 'CursorHoldI' }, {
--               buffer = event.buf,
--               group = highlight_augroup,
--               callback = vim.lsp.buf.document_highlight,
--             })
--
--             vim.api.nvim_create_autocmd({ 'CursorMoved', 'CursorMovedI' }, {
--               buffer = event.buf,
--               group = highlight_augroup,
--               callback = vim.lsp.buf.clear_references,
--             })
--
--             vim.api.nvim_create_autocmd('LspDetach', {
--               group = vim.api.nvim_create_augroup('lsp-detach', { clear = true }),
--               callback = function(event2)
--                 vim.lsp.buf.clear_references()
--                 vim.api.nvim_clear_autocmds({ group = 'lsp-highlight', buffer = event2.buf })
--               end,
--             })
--           end
--
--           -- The following code creates a keymap to toggle inlay hints in your
--           -- code, if the language server you are using supports them
--           --
--           -- This may be unwanted, since they displace some of your code
--           if client and client_supports_method(client, vim.lsp.protocol.Methods.textDocument_inlayHint, event.buf) then
--             map('<leader>gth', function()
--               vim.lsp.inlay_hint.enable(not vim.lsp.inlay_hint.is_enabled { bufnr = event.buf })
--             end, '[T]oggle Inlay [H]ints')
--           end
--         end,
--       })
--
--     end,
--   },
-- }
